export const userActionType = {
	REGISTER_USER: 'REGISTER_USER',
	UPDATE_USER: 'UPDATE_USER',
	GET_LOGIN_DATA_USER: 'GET_LOGIN_DATA_USER',
	LOGIN_USER: 'LOGIN_USER',
	LOGOUT_USER: 'LOGOUT_USER',
	REQUEST_REGISTRATION_CODE_USER: 'REQUEST_REGISTRATION_CODE_USER',
	CHECK_REGISTRATION_CODE_USER: 'CHECK_REGISTRATION_CODE_USER',
	SUCCESS_USER: 'SUCCESS_USER',
	ERROR_USER: 'ERROR_USER'
}

export const storeActionType = {
	REGISTER_STORE: 'REGISTER_STORE',
	LIST_STORE: 'LIST_STORE',
	SUCCESS_STORE: 'SUCCESS_STORE',
	ERROR_STORE: 'ERROR_STORE'
}

export const countryActionType = {
	REGISTER_COUNTRY: 'REGISTER_COUNTRY',
	LIST_COUNTRY: 'LIST_COUNTRY',
	SUCCESS_COUNTRY: 'SUCCESS_COUNTRY',
	ERROR_COUNTRY: 'ERROR_COUNTRY'
}

export const cryptocoinActionType = {
	LIST_CRYPTOCOIN: 'LIST_CRYPTOCOIN',
	CREATE_CRYPTOCOIN: 'CREATE_CRYPTOCOIN',
	SUCCESS_CRYPTOCOIN: 'SUCCESS_CRYPTOCOIN',
	ERROR_CRYPTOCOIN: 'ERROR_CRYPTOCOIN'
}

export const contactActionType = {
	LIST_CONTACT: 'LIST_CONTACT',
	REGISTER_CONTACT: 'REGISTER_CONTACT',
	UPDATE_CONTACT: 'UPDATE_CONTACT',
	DELETE_CONTACT: 'DELETE_CONTACT',
	SUCCESS_CONTACT: 'SUCCESS_CONTACT',
	ERROR_CONTACT: 'ERROR_CONTACT'
}

export const seederActionType = {
	LIST_RANDOM_SEEDER: 'LIST_RANDOM_SEEDER',
	SUCCESS_SEEDER: 'SUCCESS_SEEDER',
	ERROR_SEEDER: 'ERROR_SEEDER'
}

export const transactionActionType = {
	LIST_TRANSACTION: 'LIST_TRANSACTION',
	SEND_TRANSACTION: 'SEND_TRANSACTION',
	UPDATE_TRANSACTION: 'UPDATE_TRANSACTION',
	DELETE_TRANSACTION: 'DELETE_TRANSACTION',
	SUCCESS_TRANSACTION: 'SUCCESS_TRANSACTION',
	ERROR_TRANSACTION: 'ERROR_TRANSACTION'
}

export const balanceActionType = {
	SET_BALANCE: 'SET_BALANCE'
}